### ISSUE TITLE
Failed to convert the TensorFlow model to a PyTorch model

### ISSUE THREAD

**Issue by HHansi** [digitalepidemiologylab/covid-twitter-bert#10]
Hi,
Thank you for the wonderful model and repository in these much needed time.

I tried to convert covid-twitter-bert TensorFlow model, which was downloaded from TF2 Checkpoint to a PyTorch model using Hugging Face [TensorFlow checkpoint conversion](https://huggingface.co/transformers/converting_tensorflow_models.html#bert) (Used transformers version 3.0.0). But, I could not succeed due to the following error occurred. 
```
INFO:transformers.modeling_bert:Skipping _CHECKPOINTABLE_OBJECT_GRAPH
Traceback (most recent call last):
  File "/usr/local/bin/transformers-cli", line 32, in <module>
    service.run()
  File "/usr/local/lib/python3.6/dist-packages/transformers/commands/convert.py", line 78, in run
    convert_tf_checkpoint_to_pytorch(self._tf_checkpoint, self._config, self._pytorch_dump_output)
  File "/usr/local/lib/python3.6/dist-packages/transformers/convert_bert_original_tf_checkpoint_to_pytorch.py", line 36, in convert_tf_checkpoint_to_pytorch
    load_tf_weights_in_bert(model, config, tf_checkpoint_path)
  File "/usr/local/lib/python3.6/dist-packages/transformers/modeling_bert.py", line 124, in load_tf_weights_in_bert
    assert pointer.shape == array.shape
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'BertForPreTraining' object has no attribute 'shape'
```
Same conversion method was used with BERT-base (cased_L-12_H-768_A-12) TensorFlow model and it converted successfully. Therefore, I assume this error is specific to covid-twitter-bert model. 
Comparing with other BERT TensorFlow models, I found that covid-twitter-bert TensorFlow model missing a .meta file and I suspect it can be a possible reason for this error. 

If this error is occurred due to missing .meta file, can you please provide this file? Otherwise, do you have any solution for this issue or can you make a PyTorch model available?

**Comment by mar-muel** [comment]
Dear HHansi

Thanks for looking into this. I've tried this and also got stuck at the same place. I think I found that the script only works for models trained with the original bert implementation (found [here](https://github.com/google-research/bert)) and not with the [TF2.x implementation](https://github.com/tensorflow/models/tree/master/official/nlp/bert). Converting our model to PyTorch is very high on my todo-list though. The script can still be used, one just has to adapt to the new variable names in BERT TF2.x. Let me know if you find a suitable script - PRs are always welcome ofc 😄

**Comment by HHansi** [comment]
Dear mar-muel,

Thank you for your response. 
I'll let you know if I could find a solution.

**Comment by mar-muel** [comment]
Hi Hansi

Just to let you know that I have now converted the model into a native PyTorch model (I wrote my own script, see [here](https://github.com/digitalepidemiologylab/covid-twitter-bert/blob/master/convert_tf2_to_pytorch/convert_tf2_to_pytorch_pretrain.py), if you're interested).

You can now use our model like any other model, e.g.:
```python
from transformers import BertForPreTraining

model = BertForPreTraining.from_pretrained('digitalepidemiologylab/covid-twitter-bert')
```

Hope this helps!

**Comment by HHansi** [comment]
Hi Martin,

Thank you very much.
This really helps a lot.
