### ISSUE TITLE
CUDA out of memory Error from loading CT-Bert directly from Huggingface

### ISSUE THREAD

**Issue by nazaninj72** [digitalepidemiologylab/covid-twitter-bert#12]
I was trying to fine tune CT-Bert in my own data and I have created a very simple classifier on top of CT-Bert. I used the 
`from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("digitalepidemiologylab/covid-twitter-bert")

model = AutoModel.from_pretrained("digitalepidemiologylab/covid-twitter-bert")`
as suggested.
However, in training the model in a cluster with 10GB of memory I am getting this error:

RuntimeError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 10.73 GiB total capacity; 9.54 GiB already allocated; 19.56 MiB free; 9.86 GiB reserved in total by PyTorch)

I tried same classifier with `bert-base-uncased` model. I did not encounter this problem. 
So I was wondering if the model is too large for a gpu cluster or should I do something extra?

**Comment by mar-muel** [comment]
Hi! 

Yes, unfortunately our model is of `bert-large-uncased` type originally and therefore on a Colab GPU you can only run batch sizes of 8.

If you reduce `max_seq_length` you might get bigger batch sizes. Check how much would get truncated if you reduced max_seq_length to something like 70 or 80. If you work with tweets you can sometimes safely reduce it and run bigger batch sizes. 

Also check out our Colab using TF 2.x on TPU which allows you to use bigger batches. We've now added a Colab for both GPU and TPU training to the README. Let me know if this works for you.

**Comment by nazaninj72** [comment]
Thank you smaller batch size worked in my case. 
I tried to reduce max_seq_length but it affects my performance. So I will stick to smaller batch size for now. Thanks!
