### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by morganmcg1** [digitalepidemiologylab/covid-twitter-bert#13]
Hi all,

Thanks for sharing a great paper and accompanying code! I would love to re-use some of your text processing functions elsewhere (probably as part of a PR to an open source library), however you haven't defined a license file for the repo. Without it:

> all rights are reserved and it is not Open Source or Free. You cannot modify or redistribute this code without explicit permission from the copyright holder.

Would you consider a more open source friendly license? :)

**Comment by mar-muel** [comment]
Thanks for the note, @morganmcg1  - seems like I forgot to add it. It is now under MIT. 

Cheers!

**Comment by morganmcg1** [comment]
Super, thank you!
