### ISSUE TITLE
Make one over CORD-19

### ISSUE THREAD

**Issue by impredicative** [digitalepidemiologylab/covid-twitter-bert#2]
How about another pretrained model over [CORD-19](https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge)? It would be more scientifically relevant. Thanks.

**Comment by mar-muel** [comment]
Hi @impredicative Thanks for your input! 

Our model is intended to be used for analysis of social media data (in particular from Twitter) and not to search scientific literature.
