### ISSUE TITLE
What are the tokens for Usernames and Hastags in the BERT vocabulary?

### ISSUE THREAD

**Issue by abaheti95** [digitalepidemiologylab/covid-twitter-bert#8]
In the paper, it is mentioned "Each tweet was pseudonymized by replacing all Twitter usernames with a common text token. A similar procedure was performed on all URLs to web pages. We also replaced all unicode emoticons with textual ASCII representations (e.g. :smile: for ☺️ ) using the Python emoji library"

But it is not exactly clear which exact tokens are used in-place of usernames and URLs. Are they documented anywhere?

**Comment by mar-muel** [comment]
Hi Ashutosh! This is a good question and I'm not sure if what we're doing is the best. For urls we are using `twitterurl` and for user mentions `twitteruser`. These get tokenized like so:
```python
# twitterurl
['twitter', '##ur', '##l']
# twitteruser
```
