### ISSUE TITLE
Download Twitter-Sentiment SemEval

### ISSUE THREAD

**Issue by gbaert** [digitalepidemiologylab/covid-twitter-bert#9]
Hi, 

I want to try to reproduce your results on the SemEval 2016 Task 4 dataset (http://alt.qcri.org/semeval2016/task4/index.php?id=data-and-tools) but the download link provided give only the Ids of the tweets. I tried to download its with the Twitter API, but it appears there are a lot of 404 Errors when trying to get the tweets. 

Do  you have any solution ?

**Comment by mar-muel** [comment]
Hey - It seems like they have removed the data in the meantime 🤔  I don't think I'm allowed to publish the data here on Github so best you send me an [email](mailto:martin.muller@epfl.ch) and I can send you the dataset directly.

**Comment by Uingll** [comment]
Hello, can you send me the covid-19 category (CC) dataset? My email is 1271013240@qq.com Because I only provided the ID of twitter, I can't get any other content. Thank you very much

**Comment by zhijing-jin** [comment]
Hi is there a downloadable version of your SemEval Twitter classifier?
